---

blueprint: 
  - Standalone Server
  - Standalone Volume
  - Standalone Security Group
subscription:
  - Set membership criteria of Security Group
catalog-entitlement:
  - Set Segment Port Tags
workflow-custom-form:
  - Set Segment Port Tags
