---

blueprint: 
  - Standalone Server
  - Standalone Volume
  - Standalone Security Group
subscription:
  - Set membership criteria of Security Group
  - Update VM NICs MAC addresses
workflow-custom-form:
  - Set Segment Port Tags
